language: python

sudo: required
dist: trusty
group: edge

services:
  - docker

matrix:
  fast_finish: true

env:
  - IMAGE_BUILD_PLATFORM=stable-centos7
  - IMAGE_BUILD_PLATFORM=devel-centos7
  - IMAGE_BUILD_PLATFORM=fgcislurm1702
  - IMAGE_BUILD_PLATFORM=fgcislurm1605
  - IMAGE_BUILD_PLATFORM=fgcislurm1508

install:
  - npm install -g validate-dockerfile
before_script:
  # TESTDIR = Where the stable-centos/Dockerfile is located
  - export TESTDIR=tests
  # ROLETOTEST = The name of this repo
  - export ROLETOTEST=$(basename $(pwd))
  - export COMMIT=${TRAVIS_COMMIT::8}
  # The tag we assign the docker image we build with the Dockerfile
  - export REPO=csc/ansible
  # https://www.npmjs.com/package/validate-dockerfile - validate the Dockerfile
  - docklint ${TESTDIR}/${IMAGE_BUILD_PLATFORM}/Dockerfile
  # Build the image
  - docker build -t ${REPO}:${IMAGE_BUILD_PLATFORM} ${TESTDIR}/${IMAGE_BUILD_PLATFORM}/
  # Launch the container
  - docker run --privileged -d -ti -e "container=docker"  -v `pwd`:/$ROLETOTEST -v /sys/fs/cgroup:/sys/fs/cgroup  ${REPO}:${IMAGE_BUILD_PLATFORM}  /usr/sbin/init
  - DOCKER_CONTAINER_ID=$(docker ps | grep ${IMAGE_BUILD_PLATFORM} | awk '{print $1}')
  - docker logs $DOCKER_CONTAINER_ID

script:
  # Testing of this ansible-role:
  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c "/$ROLETOTEST/tests/test-in-docker-image.sh $IMAGE_BUILD_PLATFORM"
after_script:
  - >
    docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'echo -ne "------\nEND ANSIBLE TESTS\n------\nSystemD Units:\n------\n";
       systemctl --no-pager --all --full status ;
       echo -ne "------\nJournalD Logs:\n------\n" ;
       sudo journalctl --catalog --all --full --no-pager'
  - docker exec -ti $DOCKER_CONTAINER_ID /bin/sh -c 'tree /ansible*'
  - docker ps -a
  - docker stop $DOCKER_CONTAINER_ID
  - docker rm -v $DOCKER_CONTAINER_ID

notifications:
  email: false
  flowdock:
    secure: "lslFw8kG2GmnBoI2SfpvBqqJm9MJOi9XwgJDnIMOd7mWCaw0SUngUGPyfGHsZzK4pnzZhGMWPkXAtcvHCCIxfJYl+J91dxHVXhGz17HuQnZhmspcZD2dIW2wUVDdlCg7GXTHt/k8sgjLZOKWF4kjGDCqspU2u/wFaRBFM7ekkUjwTr9OLn/afZa7hgH7rTtj6Eg5gcC94aolEisnVv1FAQrOrIL+vxnYD+f9LTNu83NwP8eifrKoNdnYBZPRrs9hxmTrGrvgtDzu3p6YWYxxJFFxqQtSuUbgCsuZWUn/24vbnAShoRATeboGZzFgknU8zwFHkPB53Yd9wyLulV3PvTHYi9oVkg6ZjmUhPxvLYyYoRzAIcEx64m3MquUtnvKN0031vwicSLXjeu5DzemL5/ZbXiN6zRHclsuPFYE4xedHfvbpgzhsZjTDnZc59EZn1M8YbiOKzET32Q5JNVFhsH8j4VcftWjOx/hRFpqmbJHii2CpbctK1WiiGsKN5emoe/bqSucadtSZNUeTbFct7x5S2G6vOlWCMREB1DW9A/BzxOy7j255/1mcBips2i5H677+CVRQ8fPMspLwDcuO4HQBHvWz44gQN+bYI51+kdX4pkTT6dx+OyRlLqVrg6h1eSnu4rJKzbhNk7iaZPJ9izn6TsGneI3hhlUU2+b0mO0="
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
