---
    # Set slurm user and group locally on every host if uid/gid given
  - name: add slurm unix group
    group: name=slurm system=no state=present gid={{ slurm_user_gid|default(slurm_user_uid) }}
    register: reg_slurm_unixgroup
    when: slurm_user_uid is defined

  - name: add slurm unix user
    user: name=slurm shell=/sbin/nologin createhome=no system=no append=yes group=slurm state=present uid={{ slurm_user_uid }}
    register: reg_slurm_unixuser
    when: slurm_user_uid is defined

  - name: install common Slurm packages
    apt: name="{{ slurm_packages }}" state=present update_cache=yes allow_unauthenticated=yes
    when: slurm_packages.0 != ""

  - name: install fgci Slurm addons
    package: name=slurm-fgi-addons state=present
    when: slurm_repo == 'fgci'

  - name: Copy pam.d/slurm
    copy: src=pam_slurm dest=/etc/pam.d/slurm owner=root mode=0644

  - name: Make from template cgroup.conf
    template: src=cgroup.conf.j2 dest=/etc/slurm/cgroup.conf owner=root mode=0644 backup=yes
    notify: restart slurm

  - name: Make from template gres.conf
    template: src=gres.conf.j2 dest=/etc/slurm/gres.conf owner=root mode=0644
    notify: restart slurm

  - name: Make from template topology.conf
    template: src=topology.conf.j2 dest=/etc/slurm/topology.conf owner=root mode=0644
    notify: restart slurm
    when: slurm_topology_plugin is defined

  - name: Make from template slurm.conf
    template: src=slurm.conf.j2 dest=/etc/slurm/slurm.conf owner=root mode=0644 backup=yes
    notify: restart slurm

  - name: write all slurm logs handled by rsyslog to one file
    template: src=slurm_rsyslog.conf dest=/etc/rsyslog.d/10_slurm_rsyslog.conf owner=root mode=0644 backup=yes
    notify: Restart rsyslog
    when: slurm_manage_rsyslog_conf|bool

  - name: configure logrotate to rotate slurm_logs in slurm_log_dir
    template: src=slurm_logrotate.j2 dest=/etc/logrotate.d/slurm owner=root mode=0644 backup=no
    when: slurm_log_dir is defined

  - name: template in plugstack.conf
    template: src=plugstack.conf.j2 dest=/etc/slurm/plugstack.conf owner=root mode=0644 backup=yes
    when: slurm_plugstack|bool

  - name: create slurm/plugstack.conf.d
    file: path=/etc/slurm/plugstack.conf.d state=directory owner=root group=root mode=0755
    when: slurm_plugstack|bool

  - name: template in plugstack.conf.d/x11.conf
    template: src=x11.conf.j2 dest=/etc/slurm/plugstack.conf.d/x11.conf owner=root mode=0644 backup=no
    when: slurm_plugstack|bool and slurm_x11_spank|bool

  - name: install slurm-spank-x11 and xauth
    package: name="{{ slurm_spank_x11_packages }}" state=present
    when: slurm_plugstack|bool and slurm_x11_spank|bool
