---

  - name: copy munge key to submit node
    copy: src=files/munge.key
          dest=/etc/munge/munge.key
          owner=munge
          group=munge
          mode=0400
    notify:
     - restart munge
          
  - name: start and enable munge
    service: name=munge state=started enabled=yes
    when: ansible_connection != 'chroot'

  - name: Enable munge in chroot
    command: systemctl enable munge
    when: ansible_connection == 'chroot'
